# Generated by Django 2.2.6 on 2019-10-28 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Назва книги')),
                ('book_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип книги')),
                ('number', models.SmallIntegerField(blank=True, null=True, verbose_name='Номер видання')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Видавництво')),
                ('city_of_publication', models.CharField(blank=True, max_length=255, null=True, verbose_name='Місто видання')),
                ('year', models.SmallIntegerField(blank=True, null=True, verbose_name='Рік видання')),
                ('number_of_pages', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кількість сторінок')),
                ('extra_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='Додаткова інформація')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AuthorEditorTranslator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_name', models.CharField(max_length=50, verbose_name='Ім’я')),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('patronymic', models.CharField(max_length=50, verbose_name='По батькові')),
                ('_type', models.CharField(choices=[('au', 'author'), ('ed', 'editor'), ('tr', 'translator')], default='au', max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Book')),
            ],
        ),
    ]
