# Generated by Django 2.2.6 on 2019-10-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authoreditortranslator',
            old_name='firt_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='authoreditortranslator',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_e_t', to='sources.Book'),
        ),
    ]
