# Generated by Django 2.2.6 on 2019-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20191029_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoreditortranslator',
            name='lang',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
