# Generated by Django 2.2.6 on 2019-10-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_authoreditortranslator_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoreditortranslator',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='sources.Book'),
        ),
    ]
